import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative h-[70dvh] mx-auto bg-[#eeeeee]">
          <div className="absolute h-full w-[50%] right-0 bg-[#31363f] rounded-[35px] z-0"></div>
          <div className="absolute flex h-full items-center justify-start z-0">
            <div className="h-[40px] w-[40px] bg-[#31363f] ml-[-25px] rotate-45"></div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
